import main
import matplotlib.pyplot as plt

BC1_F = main.count_nucleotides("BC1.F.map")
BC1_R = main.count_nucleotides("BC1.R.map")
BC2_F = main.count_nucleotides("BC2.F.map")
BC2_R = main.count_nucleotides("BC2.R.map")
BC3_F = main.count_nucleotides("BC3.F.map")
BC3_R = main.count_nucleotides("BC3.R.map")
BC4_F = main.count_nucleotides("BC4.F.map")
BC4_R = main.count_nucleotides("BC4.R.map")
BC5_F = main.count_nucleotides("BC5.F.map")
BC5_R = main.count_nucleotides("BC5.R.map")
BC6_F = main.count_nucleotides("BC6.F.map")
BC6_R = main.count_nucleotides("BC6.R.map")
BC7_F = main.count_nucleotides("BC7.F.map")
BC7_R = main.count_nucleotides("BC7.R.map")
BC8_F = main.count_nucleotides("BC8.F.map")
BC8_R = main.count_nucleotides("BC8.R.map")
BC9_F = main.count_nucleotides("BC9.F.map")
BC9_R = main.count_nucleotides("BC9.R.map")
BC10_F = main.count_nucleotides("BC10.F.map")
BC10_R = main.count_nucleotides("BC10.R.map")

BC1_F_mutations = main.calculate_mutations((BC1_F))
BC1_R_mutations = main.calculate_mutations((BC1_R))
BC2_F_mutations = main.calculate_mutations((BC2_F))
BC2_R_mutations = main.calculate_mutations((BC2_R))
BC3_F_mutations = main.calculate_mutations((BC3_F))
BC3_R_mutations = main.calculate_mutations((BC3_R))
BC4_F_mutations = main.calculate_mutations((BC4_F))
BC4_R_mutations = main.calculate_mutations((BC4_R))
BC5_F_mutations = main.calculate_mutations((BC5_F))
BC5_R_mutations = main.calculate_mutations((BC5_R))
BC6_F_mutations = main.calculate_mutations((BC6_F))
BC6_R_mutations = main.calculate_mutations((BC6_R))
BC7_F_mutations = main.calculate_mutations((BC7_F))
BC7_R_mutations = main.calculate_mutations((BC7_R))
BC8_F_mutations = main.calculate_mutations((BC8_F))
BC8_R_mutations = main.calculate_mutations((BC8_R))
BC9_F_mutations = main.calculate_mutations((BC9_F))
BC9_R_mutations = main.calculate_mutations((BC9_R))
BC10_F_mutations = main.calculate_mutations((BC10_F))
BC10_R_mutations = main.calculate_mutations((BC10_R))

BC1_F_plot = main.plot_mutation_base_proberbility(BC1_F, BC1_F_mutations)
plt.savefig("BC1_F.png")
BC1_R_plot = main.plot_mutation_base_proberbility(BC1_R, BC1_R_mutations)
plt.savefig("BC1_R.png")
BC2_F_plot = main.plot_mutation_base_proberbility(BC2_F, BC2_F_mutations)
plt.savefig("BC2_F.png")
BC2_R_plot = main.plot_mutation_base_proberbility(BC2_R, BC2_R_mutations)
plt.savefig("BC2_R.png")
BC3_F_plot = main.plot_mutation_base_proberbility(BC3_F, BC3_F_mutations)
plt.savefig("BC3_3.png")
BC3_R_plot = main.plot_mutation_base_proberbility(BC3_R, BC3_R_mutations)
plt.savefig("BC3_R.png")
BC4_F_plot = main.plot_mutation_base_proberbility(BC4_F, BC4_F_mutations)
plt.savefig("BC4_F.png")
BC4_R_plot = main.plot_mutation_base_proberbility(BC4_R, BC4_R_mutations)
plt.savefig("BC4_R.png")
BC5_F_plot = main.plot_mutation_base_proberbility(BC5_F, BC5_F_mutations)
plt.savefig("BC5_F.png")
BC5_R_plot = main.plot_mutation_base_proberbility(BC5_R, BC5_R_mutations)
plt.savefig("BC5_R.png")
BC6_F_plot = main.plot_mutation_base_proberbility(BC6_F, BC6_F_mutations)
plt.savefig("BC6_F.png")
BC6_R_plot = main.plot_mutation_base_proberbility(BC6_R, BC6_R_mutations)
plt.savefig("BC6_R.png")
BC7_F_plot = main.plot_mutation_base_proberbility(BC7_F, BC7_F_mutations)
plt.savefig("BC7_F.png")
BC7_R_plot = main.plot_mutation_base_proberbility(BC7_R, BC7_R_mutations)
plt.savefig("BC7_R.png")
BC8_F_plot = main.plot_mutation_base_proberbility(BC8_F, BC8_F_mutations)
plt.savefig("BC8_F.png")
BC8_R_plot = main.plot_mutation_base_proberbility(BC8_R, BC8_R_mutations)
plt.savefig("BC8_R.png")
BC9_F_plot = main.plot_mutation_base_proberbility(BC9_F, BC9_F_mutations)
plt.savefig("BC9_F.png")
BC9_R_plot = main.plot_mutation_base_proberbility(BC9_R, BC9_R_mutations)
plt.savefig("BC9_R.png")
BC10_F_plot = main.plot_mutation_base_proberbility(BC10_F, BC10_F_mutations)
plt.savefig("BC10_F.png")
BC10_R_plot = main.plot_mutation_base_proberbility(BC10_R, BC10_R_mutations)
plt.savefig("BC10_R.png")

